"""add column surname 

Revision ID: bacd24185044
Revises: bc5e1524f424
Create Date: 2025-05-26 14:17:40.240051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bacd24185044'
down_revision: Union[str, None] = 'bc5e1524f424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_sale', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('surname', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'surname')
    op.drop_column('users', 'has_sale')
    # ### end Alembic commands ###
